export const ROUTES = {
  INICIO: '/',
  AUTH_LOGIN: '/auth/login',
  AUTH_REGISTER: '/auth/register',
  DASHBOARD_FUNCIONARIOS: '/dashboard/funcionarios',
  DASHBOARD_ESTRUCTURA_ORGANIZACIONAL: '/dashboard/estructura',
  DASHBOARD_UTILERIAS: '/dashboard/utilerias',
  DASHBOARD_CATALOGO: '/dashboard/catalogo',
  GESTION_DASHBOARD: '/gestion',
  GESTION_DELEGACIONES: '/gestion/delegaciones',
  CREATE_DELEGACION: '/gestion/delegaciones/create',
  GESTION_DEPENDENCIAS: '/gestion/dependencias',
  CREATE_DEPENDENCIA: '/gestion/dependencias/create',
  GESTION_FUNCIONARIOS: '/gestion/funcionarios',
  CREATE_FUNCIONARIO: '/gestion/funcionarios/create',
  GESTION_UTILERIAS: '/gestion/utilerias',
}