# version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: database_development      
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: database_development
      DB_USER: root
      DB_PASS: 123456
    depends_on:
      - db
    command: sh -c "npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && npm start" 
    volumes:
      - ./Server:/app
  
  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    image: frontend-app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./Client:/app:cached
      - /app/node_modules

volumes:
  db_data:
