# Usa una imagen base de Node
FROM node:20

# Crea el directorio de la app
WORKDIR /app

# Copia los archivos de Node
COPY package*.json ./

# Instala dependencias
RUN npm install

# Copia el resto del código fuente
COPY . .

# Expone el puerto de tu app
EXPOSE 3000

# Comando para correr la app
CMD ["npm", "run" ,"dev"]
