name: Build and Run with Docker Compose

on:
  pull_request:
    types: [closed]

jobs:
  build-container:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d
